/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/R9MrG7Z8IaL
 */

export function CreateNFT() {
  return (
    <div
      key="1"
      className="bg-gradient-to-br from-red-600 to-purple-800 text-gray-200 min-h-screen"
    >
      <header className="bg-gradient-to-r from-red-800 to-purple-600 p-4 flex justify-between items-center">
        <h1 className="text-2xl font-bold">Content Upload and AI Editing</h1>
      </header>
      <main className="p-8 grid grid-cols-2 gap-8">
        <div className="flex flex-col items-center">
          <div className="w-full max-w-lg bg-gray-200 rounded-lg p-6 shadow-md">
            <h2 className="text-xl font-bold mb-4 text-purple-900">
              File Upload
            </h2>
            <div className="flex justify-center items-center h-48 bg-gray-300 rounded-lg mb-4">
              <button className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">
                Upload File
              </button>
            </div>
            <div className="h-48 bg-gray-300 rounded-lg">
              <img
                alt="Preview"
                className="w-full h-full object-contain"
                height="192"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "192/192",
                  objectFit: "cover",
                }}
                width="192"
              />
            </div>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <div className="w-full max-w-lg bg-gradient-to-b from-red-800 via-purple-700 to-red-600 rounded-lg p-6 shadow-md">
            <h2 className="text-xl font-bold mb-4">AI Editing Tools</h2>
            <div className="grid grid-cols-3 gap-4">
              <button className="bg-gradient-to-r from-red-700 to-purple-800 p-4 rounded-lg flex flex-col items-center justify-center hover:bg-gradient-to-r hover:from-red-600 hover:to-purple-700">
                <img
                  alt="Image Filter"
                  className="mb-2"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span>Image Filter</span>
              </button>
              <button className="bg-gradient-to-r from-red-700 to-purple-800 p-4 rounded-lg flex flex-col items-center justify-center hover:bg-gradient-to-r hover:from-red-600 hover:to-purple-700">
                <img
                  alt="Text Recognition"
                  className="mb-2"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span>Text Recognition</span>
              </button>
              <button className="bg-gradient-to-r from-red-700 to-purple-800 p-4 rounded-lg flex flex-col items-center justify-center hover:bg-gradient-to-r hover:from-red-600 hover:to-purple-700">
                <img
                  alt="Object Detection"
                  className="mb-2"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span>Object Detection</span>
              </button>
            </div>
            <div className="mt-8">
              <h3 className="text-lg font-bold mb-2">Tool Options</h3>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-gradient-to-r from-red-800 to-purple-600 p-4 flex justify-end">
        <button className="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
          Save
        </button>
      </footer>
    </div>
  );
}
